# Generated by Django 5.0.6 on 2024-05-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_unidademedida_produto_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidademedida',
            name='unidade',
            field=models.CharField(max_length=3),
        ),
    ]
