# Generated by Django 5.0.6 on 2024-05-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_unidademedida_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidademedida',
            name='unidade',
            field=models.CharField(max_length=30),
        ),
    ]
