# Generated by Django 5.0.6 on 2024-05-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_unidademedida_unidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_quantidade', models.IntegerField()),
                ('tot_valor', models.FloatField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_registro'],
            },
        ),
    ]
