# Generated by Django 5.0.6 on 2024-05-14 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_produtoinventario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtoinventario',
            old_name='tot_quantidade',
            new_name='tot_produtos',
        ),
    ]
