# Generated by Django 5.0.6 on 2024-05-15 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_rename_tot_quantidade_produtoinventario_tot_produtos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='valor',
            new_name='valor_unidade',
        ),
    ]
