# Generated by Django 5.0.6 on 2024-05-15 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_rename_valor_produto_valor_unidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtoinventario',
            name='tot_valor',
        ),
    ]
