# Generated by Django 5.0.6 on 2024-05-15 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_remove_produtoinventario_tot_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='tipo',
            new_name='categoria',
        ),
    ]
