# Generated by Django 5.0.6 on 2024-05-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_rename_tipo_produto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assunto', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('data_feedback', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackContagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_feedback', models.IntegerField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
