# Generated by Django 5.0.6 on 2024-05-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0011_feedback_feedbackcontagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='nome',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
