# Generated by Django 5.0.6 on 2024-05-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0012_feedback_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='profissao',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
