# Generated by Django 5.0.6 on 2024-05-16 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_feedback_profissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='profissao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_profissao', to='estoque.profissao'),
        ),
    ]
