# Generated by Django 5.0.6 on 2024-05-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0014_profissao_alter_feedback_profissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=60)),
                ('cargo', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('data_contratacao', models.DateField()),
            ],
        ),
    ]
